name: Analysis

on:
  push:
  pull_request:

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
      - name: vet
        run: |
          go vet ./...
